name       : kio-fuse
version    : 5.0.1
release    : 2
source     :
    - https://cdn.download.kde.org/stable/kio-fuse/5.0.1/kio-fuse-5.0.1.tar.xz : 66679a8bf68fe60e19f31449f4110d4cf822915b3d245af3c0cd0056081466dd
license    : GPL-3.0-or-later
component  : network.util
summary    : FUSE interface for KIO
description: |
    FUSE interface for KIO
builddeps  :
    - pkgconfig(fuse3)
    - kio-devel
rundeps    :
    - fuse
setup      : |
    %cmake_ninja -DBUILD_TESTING=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
